name       : libconfuse
version    : '3.3'
release    : 7
source     :
    - https://github.com/libconfuse/libconfuse/releases/download/v3.3/confuse-3.3.tar.xz : 1dd50a0320e135a55025b23fcdbb3f0a81913b6d0b0a9df8cc2fdf3b3dc67010
homepage   : http://www.nongnu.org/confuse
license    : ISC
component  : desktop.library
summary    : C-library for parsing configuration files
description: |
    C-library for parsing configuration files
setup      : |
    %reconfigure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
