name       : libconfuse
version    : '2.7'
release    : 4
source     :
    - https://github.com/martinh/libconfuse/archive/v2.7.tar.gz : 07ffe1bc4f9bd16a952a222dd978d049db4deb5f7d448652cbb4c1229acd67c8
homepage   : http://www.nongnu.org/confuse
license    : GPL-2.0
component  : desktop.library
summary    : C-library for parsing configuration files
description: |
    C-library for parsing configuration files
setup      : |
    %reconfigure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
