name        : libconfuse
version     : 2.7
release     : 3
source      :
    - http://savannah.nongnu.org/download/confuse/confuse-2.7.tar.gz : e32574fd837e950778dac7ade40787dd2259ef8e28acd6ede6847ca895c88778
homepage    : http://www.nongnu.org/confuse
license     : GPL-2.0
component   : desktop.library
summary     : C-library for parsing configuration files
description : |
    C-library for parsing configuration files
setup      : |
    %configure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
